# Generated by Django 5.2.9 on 2026-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
