# Generated by Django 5.2.9 on 2026-01-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_income_payment_mode_income_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='source',
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_mode',
            field=models.CharField(default='Cash', max_length=20),
            preserve_default=False,
        ),
    ]
